"""Stable domain enumerations."""

from enum import Enum


class StrEnum(str, Enum):
    """Python 3.10-compatible string enum."""

    def __str__(self) -> str:
        return str(self.value)


class RunState(StrEnum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    RUNNING = "RUNNING"
    PAUSE_REQUESTED = "PAUSE_REQUESTED"
    PAUSED = "PAUSED"
    RECOVERING = "RECOVERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskState(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    PAUSE_REQUESTED = "PAUSE_REQUESTED"
    PAUSED = "PAUSED"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class FailurePolicy(StrEnum):
    RETRY = "RETRY"
    FAIL_RUN = "FAIL_RUN"
    SKIP_DEPENDENTS = "SKIP_DEPENDENTS"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class CheckpointPolicy(StrEnum):
    BEFORE_AND_AFTER = "BEFORE_AND_AFTER"
    AFTER = "AFTER"
    RUN_BOUNDARY = "RUN_BOUNDARY"


class ErrorCategory(StrEnum):
    VALIDATION = "VALIDATION"
    PROVIDER_RETRYABLE = "PROVIDER_RETRYABLE"
    RATE_LIMIT = "RATE_LIMIT"
    TIMEOUT = "TIMEOUT"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    DATABASE = "DATABASE"
    CONCURRENCY = "CONCURRENCY"
    REPOSITORY_CHANGED = "REPOSITORY_CHANGED"
    CORRUPT_CHECKPOINT = "CORRUPT_CHECKPOINT"
    UNSUPPORTED_SCHEMA = "UNSUPPORTED_SCHEMA"
    SECURITY_POLICY = "SECURITY_POLICY"
    TERMINAL_DOMAIN = "TERMINAL_DOMAIN"


class ToolCallStatus(StrEnum):
    INTENT_RECORDED = "INTENT_RECORDED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    UNCERTAIN = "UNCERTAIN"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class SideEffectClass(StrEnum):
    NONE = "NONE"
    IDEMPOTENT = "IDEMPOTENT"
    REVERSIBLE = "REVERSIBLE"
    NON_IDEMPOTENT = "NON_IDEMPOTENT"


class EvidenceType(StrEnum):
    REPOSITORY_FILE = "REPOSITORY_FILE"
    REPOSITORY_SNAPSHOT = "REPOSITORY_SNAPSHOT"
    TEST_RESULT = "TEST_RESULT"
    COMMAND_RESULT = "COMMAND_RESULT"
    ARTIFACT = "ARTIFACT"
    DATABASE_RECORD = "DATABASE_RECORD"
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"
    USER_FACT = "USER_FACT"
    AGENT_INFERENCE = "AGENT_INFERENCE"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    CONFLICTING = "CONFLICTING"
    INVALID = "INVALID"


class ClaimKind(StrEnum):
    VERIFIED_FACT = "VERIFIED_FACT"
    TEST_SUPPORTED = "TEST_SUPPORTED"
    INFERENCE = "INFERENCE"
    ASSUMPTION = "ASSUMPTION"
    UNRESOLVED = "UNRESOLVED"
    LIMITATION = "LIMITATION"


class SummaryLevel(StrEnum):
    TASK = "TASK"
    TASK_GROUP = "TASK_GROUP"
    RUN = "RUN"


class RepositoryDriftPolicy(StrEnum):
    FAIL = "FAIL"
    REINDEX = "REINDEX"
    REPLAN = "REPLAN"


class FileChangeKind(StrEnum):
    NEW = "NEW"
    MODIFIED = "MODIFIED"
    UNCHANGED = "UNCHANGED"
    DELETED = "DELETED"
